app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Length


class ProfileForm(FlaskForm):
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    bio = TextAreaField("About me", validators=[Length(min=0, max=200)])
    facebook = StringField("Facebook Profile:")
    linkedin = StringField("LinkedIN Profile:")
    submit = SubmitField("Update")

app/user/__init__.py
from pathlib import Path

from flask import Blueprint
import pandas as pd

import config
from .. import db
from ..models import User

bp = Blueprint('user', __name__, url_prefix='/user')

from . import routes  # noqa


@bp.cli.command('extract_users')
def extract_users():
    user_data = []
    user_info = db.session.query(User).all()
    for user in user_info:
        full_name = user.profile.full_name if user.profile else ' '
        user_data.append(
            {
                'username': user.username,
                'email': user.email,
                'full_name': full_name,
                'post_count': len(user.posts)
            }
        )

    df = pd.DataFrame.from_dict(user_data)
    output_file_path = Path(config.basedir) / 'extract_users.csv'
    df.to_csv(output_file_path)

app/user/routes.py
from app import db
from ..models import User, Post, Follow
from app.post.forms import PostForm
from app.user import bp
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required

from app.user.forms import ProfileForm


@bp.route("/blog")
def blog():
    form = PostForm()
    posts = (
        db.session.query(Post)
        .filter(
            Post.author_id == current_user.id
               )
        .order_by(Post.created_at.desc())
        .all()
            )
    return render_template("user/blog.html", posts=posts, form=form)


@bp.route("profile/<string:username>", methods=['GET', 'POST'])
@login_required
def user(username):
    user = db.session.query(User).filter(User.username == username).first_or_404()
    return render_template('user/profile.html', user=user, username=user.username)


@bp.route("/edit_profile", methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.profile.first_name = form.first_name.data
        current_user.profile.last_name = form.last_name.data
        current_user.profile.facebook = form.facebook.data
        current_user.profile.linkedin = form.linkedin.data
        current_user.profile.bio = form.bio.data
        db.session.commit()
        flash("Your changes have been saved", category="success")
        return redirect(url_for('user.edit_profile'))
    elif request.method == 'GET':
        form.first_name.data = current_user.profile.first_name
        form.last_name.data = current_user.profile.last_name
        form.first_name.data = current_user.profile.first_name
        form.facebook.data = current_user.profile.facebook
        form.linkedin.data = current_user.profile.linkedin
        form.bio.data = current_user.profile.bio
    return render_template('user/edit_profile.html', title='Edit Profile', form=form)


@bp.route('/user/<username>/follow', methods=['POST'])
@login_required
def follow_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_to_subscribed(user):
        flash(f'You have already following {username}', category='warning')
    else:
        subscription = Follow(follower_id=current_user.id, followee_id=user.id)
        db.session.add(subscription)
        db.session.commit()
        flash(f'You are now following {username}.', 'success')
    return redirect(url_for('user.user', username=user.username))


@bp.route('/user/<username>/unfollow', methods=['POST'])
@login_required
def unfollow_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        subscription = Follow.query.filter_by(follower_id=current_user.id, followee_id=user.id).first()
        if subscription:
            db.session.delete(subscription)
            db.session.commit()
            flash(f'You have unfollowed {username}.', 'success')
        else:
            flash(f"You are not following {username}.", 'warning')
    else:
        flash('You cannot unfollow yourself.', 'danger')
    return redirect(url_for('user.user', username=user.username))


def follow_list(username):
    user = User.query.filter_by(username=username).first_or_404()
    followers = user.followers.all()
    following = user.following.all()
    return redirect(url_for('user.user', username=user.username, followers=followers, following=following))

app/templates/user/blog.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% for post in posts %}
                {% include '_post.html' %}
            {% endfor %}
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    {% if post %}
                        <h5>Edit Post</h5>
                            <form method="post" action="{{ url_for('post.edit_post', post_id=post.id) }}" novalidate>
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    <label for="title">Title</label>
                                    {{ form.title(class='form-control', id='title', placeholder='Enter title') }}
                                </div>
                                <div class="form-group">
                                    <label for="content">Content</label>
                                    {{ form.content(class='form-control', id='content', placeholder='Enter content') }}
                                </div>
                                <button type="submit" class="btn btn-primary">Update post</button>
                            </form>
                    {% else %}
                        <h5 class="card-title">Create a new post</h5>
                        <form method="post" action="{{ url_for('post.create') }}" novalidate>
                            {{ form.csrf_token }}
                            <div class="form-group">
                                <label for="title">Title</label>
                                {{ form.title(class='form-control', id='title', placeholder='Enter title') }}
                            </div>
                            <div class="form-group">
                                <label for="content">Content</label>
                                {{ form.content(class='form-control', id='content', placeholder='Enter content') }}
                            </div>
                            <button type="submit" class="btn btn-primary">Create post</button>
                        </form>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/user/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit Profile</h1>
      <form  method="post" action="">
        {{ form.csrf_token }}
          <div class="form-group row">
            <label for="inputFirstName" class="col-sm-2 col-form-label">First Name</label>
            <div class="col-sm-10">
              {{ form.first_name(class="form-control", id="inputFirstName") }}
              {% for error in form.first_name.errors %}
              <div class="alert alert-danger">{{ error }}</div>
              {% endfor %}
            </div>
          </div>
        <div class="form-group row">
          <label for="inputLastName" class="col-sm-2 col-form-label">Last Name</label>
          <div class="col-sm-10">
            {{ form.last_name(class="form-control", id="inputLastName") }}
            {% for error in form.last_name.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
          </div>
        </div>
        <div class="form-group row">
          <label for="inputFacebook" class="col-sm-2 col-form-label">Facebook</label>
          <div class="col-sm-10">
            {{ form.facebook(class="form-control", id="inputFacebook") }}
            {% for error in form.facebook.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
          </div>
        </div>
        <div class="form-group row">
          <label for="inputLinkedin" class="col-sm-2 col-form-label">LinkedIn</label>
          <div class="col-sm-10">
            {{ form.linkedin(class="form-control", id="inputLinkedin") }}
            {% for error in form.linkedin.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
          </div>
        </div>
        <div class="form-group row">
          <label for="inputBio" class="col-sm-2 col-form-label">About Me</label>
          <div class="col-sm-10">
            {{ form.bio(class="form-control", id="inputBio") }}
            {% for error in form.bio.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
      <p><a href="{{ url_for('user.user', username=current_user.username) }}">Back</a></p>
{% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Profile</h1>
        <div class="row">
            <div class="col-md-4">
                <img src="{{ user.avatar(128) }}" class="img-thumbnail mb-3" alt="">
                <div>
                    <h5>{{ user.username }}</h5>
                    <p class="text-muted">{{ user.email }}</p>
                </div>
                <p class="text-muted">{{ user.profile.first_name }}</p>
                <p class="text-muted">{{ user.profile.last_name }}</p>
                <p class="text-muted">{{ user.profile.linkedin }}</p>
                <p class="text-muted">{{ user.profile.facebook }}</p>
                <p class="text-muted">{{ user.profile.bio }}</p>
                <p class="small">Last seen: {{ user.profile.last_seen.strftime('%Y-%m-%d %H:%M:%S') }}</p>
            </div>
            <div class="mb-3">
                    <h5>Followers:</h5>
                    <ul>
                        {% for follower in user.followers %}
                            <li>{{ follower.follower.username }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <h5>Following:</h5>
                    <ul>
                        {% for followee in user.following %}
                            <li>{{ followee.followee.username }}</li>
                        {% endfor %}
                    </ul>
                </div>
              {% if user != current_user %}
        {% if not current_user.is_to_subscribed(user) %}
        <form method="post" action="{{ url_for('user.follow_user', username=user.username) }}">
            <button type="submit" class="btn btn-primary">Follow</button>
        </form>
        {% else %}
        <form method="post" action="{{ url_for('user.unfollow_user', username=user.username) }}">
            <button type="submit" class="btn btn-primary">Unfollow</button>
        </form>
        {% endif %}
        {% endif %}
                {% if user == current_user %}
                <p><a href="{{ url_for('user.edit_profile') }}">Edit your profile</a></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}