app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=100)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min=10, max=5000)])
    submit = SubmitField('Post')

app/post/__init__.py
from pathlib import Path

import click
import pandas as pd
from flask import Blueprint

import config
from ..models import User, Post

bp = Blueprint('post', __name__, url_prefix='/post')

from . import routes  # noqa


@bp.cli.command('extract_posts')
@click.argument('user_id', type=int)
def extract_posts(user_id):
    # user_id = 56 to write user_id that you want you need to write in terminal or configuration:
    #            flask post extract_posts USER_ID
    post_data = []
    user = User.query.get(user_id)
    if user:
        post_info = Post.query.filter_by(author_id=user_id).all()
    for post in post_info:
        title = post.title
        likes = len(post.likes)
        dislikes = len(post.dislikes)
        created = post.created_at
        post_data.append(
            {
                'Posts title': title,
                'Likes count': likes,
                'Dislikes count': dislikes,
                'Post created at': created
            }
        )

    df = pd.DataFrame.from_dict(post_data)
    output_file_path = Path(config.basedir) / f'{user.username}_extract_posts.csv'
    df.to_csv(output_file_path)

app/post/routes.py
from app import db
from ..models import Post, Like, Dislike
from app.post import bp
from .forms import PostForm
from flask import render_template, request, redirect, url_for, flash, abort
from flask_login import current_user, login_required


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = PostForm()

    if request.method == "POST":
        if form.validate_on_submit():
            post = Post(title=form.title.data, content=form.content.data, author=current_user)

            db.session.add(post)
            db.session.commit()
            flash('Your post has been created!', 'success')
        else:
            title = form.title.data

            if not title or len(title) < 2:
                flash('Title must be at least 3 characters long', category="error")

        return redirect(url_for("user.blog"))
    return render_template('user/blog.html', title='Create Post', form=form)


@bp.route('/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm(obj=post)
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Post has been updated!", category="success")
        return redirect(url_for("user.blog"))
    elif request.method == 'GET':
        if current_user.id == post.author_id:
            form.title.data = post.title
            form.content.data == post.content
    return render_template('user/blog.html', title='Edit Post', form=form, post=post)


@bp.route('/<int:post_id>/like', methods=['GET', 'POST'])
@login_required
def like(post_id):
    post = Post.query.get_or_404(post_id)
    liked = Like.query.filter_by(user=current_user, post=post).first()
    disliked = Dislike.query.filter_by(user=current_user, post=post).first()

    if disliked:
        db.session.delete(disliked)
        db.session.commit()
        like_post = Like(user=current_user, post=post)
        db.session.add(like_post)
        db.session.commit()
        flash('You have liked this post!', 'success')
    elif liked:
        db.session.delete(liked)
        db.session.commit()
        flash('You have  uliked this post!', 'warning')
    else:
        like_post = Like(user=current_user, post=post)
        db.session.add(like_post)
        db.session.commit()
        flash('You have liked this post!', 'success')
    return redirect(request.referrer)


@bp.route('/<int:post_id>/dislike', methods=['GET', 'POST'])
@login_required
def dislike(post_id):
    post = Post.query.get_or_404(post_id)
    liked = Like.query.filter_by(user=current_user, post=post).first()
    disliked = Dislike.query.filter_by(user=current_user, post=post).first()

    if disliked:
        db.session.delete(disliked)
        db.session.commit()
        flash('You have  udisliked this post!', 'warning')
    elif liked:
        db.session.delete(liked)
        db.session.commit()
        dislike_post = Dislike(user=current_user, post=post)
        db.session.add(dislike_post)
        db.session.commit()
        flash('You have disliked this post!', 'success')
    else:
        dislike_post = Dislike(user=current_user, post=post)
        db.session.add(dislike_post)
        db.session.commit()
        flash('You have disliked this post!', 'success')
    return redirect(request.referrer)


@bp.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('user.blog'))

app/templates/About.html
{% extends "base.html" %}

{% block title %}About{% endblock%}

{% block content %}
    About page
{% endblock %}

app/templates/_post.html
<div class="card mb-3">
    <div class="card-body d-flex align-items-center">
        <div>
            <h5 class="card-title">{{ post.title }}</h5>

            <p class="card-text">{{ post.content }}</p>
            <p class="card-text"><small class="text-muted">{{ post.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </p>
        </div>
    </div>
    <div class="card-footer">
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="{{ url_for('post.like', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                    <i class="fas fa-thumbs-up"></i>
                    {{ post.likes|length }}
                </a>
                <a href="{{ url_for('post.dislike', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                    <i class="fas fa-thumbs-down"></i> {{ post.dislikes|length }}
                </a>
                {% if request.path == url_for('user.blog') %}
                    {% if current_user == post.author %}
                        <a href="{{ url_for('post.delete', post_id=post.id) }}" class="btn btn-sm btn-outline-danger">
                            <i class="fas fxa-trash-alt"></i> Delete
                        </a>
                    {% endif %}
                {% endif %}
                {% if request.path == url_for('user.blog') %}
                    {% if current_user == post.author %}
                        <a href="{{ url_for('post.edit_post', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                            <i class="fas fa-edit"></i> Edit post
                        </a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="d-flex align-items-center">
                <a href="{{ url_for('user.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(32) }}" class="rounded-circle mr-1">
                </a>
                <span>{{ post.author.username }}</span>
            </div>
        </div>
    </div>
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>
        {% block title %}
            {% if title %}
            {{ title }}
            {% else %}
                Social Network
            {% endif %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Social Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                {% if current_user.is_authenticated %}
                <li class="nav-item{% if active == 'index' %} active{% endif %}">
                    <a class="nav-link" href="{{ url_for('user.blog') }}">Blog</a>
                </li>
                <li class="nav-item{% if active == 'index' %} active{% endif %}">
                    <a class="nav-link" href="{{ url_for('user.user', username=current_user.username) }}">Profile</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-2">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    {% endif %}
                </li>
                {% if not current_user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
          {% elif category == "success" %}
            <div class="alert alert-success">{{ message }}</div>
          {% elif category == "warning" %}
            <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous">
</script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}